### ISSUE TITLE
Cat fact page button click sometimes doesn't change picture

### ISSUE THREAD

**Issue by machado-andre** [eusouorui/CatFact#11]
The cat fact page button when clicked sometimes will not change the cat picture, only the cat fact.

(Maybe disable button when clicking it? idk)

**Comment by eusouorui** [comment]
Check if it's not loading the same image, the randomizer can be optimized to randomize another number if it initially randomizes the current one.

**Comment by eusouorui** [comment]
Button will also be disabled while content is loaded (after being pressed)
